version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: library-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: library
      MYSQL_USER: libr
      MYSQL_PASSWORD: NIEN97BF21OZEFJOZEO
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/library.sql:/docker-entrypoint-initdb.d/library.sql
    networks:
      - library-network

volumes:
  mysql_data:

networks:
  library-network:
    driver: bridge
